# Generated by Django 2.2 on 2019-04-10 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190406_0949'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee_table',
        ),
    ]
